# Generated by Django 5.2 on 2025-04-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Продолжительность в минутах"
                    ),
                ),
                ("posterUrl", models.URLField(blank=True, max_length=500, null=True)),
                ("release_date", models.DateField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
