# Generated by Django 5.2 on 2025-04-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_add_poster_url_field_to_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="posterUrl",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
