# Generated by Django 5.2 on 2025-05-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("halls", "0001_initial"),
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startTime", models.DateTimeField()),
                ("price", models.PositiveIntegerField()),
                (
                    "hallId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="halls.hall"
                    ),
                ),
                (
                    "movieId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
            ],
        ),
    ]
